apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/nginx
  - ../../base/caddy
  - ../../base/envsubst
  - ./envsubst

namespace: default

patches:
  - patch-nginx.yaml
  - patch-caddy.yaml