apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  source:
    repoURL: 'https://github.com/marwiesing/GitOps_Argo_CD.git'
    path: argo-cd
    targetRevision: main
  project: default
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
