apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-example
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/marwiesing/GitOps_Argo_CD.git'
    targetRevision: main
    path: kustomize/overlays/dev/envsubst # Change to prod for production
    plugin:
      name: envsubst-plugin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
