apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argo-cd  # Use your argo-cd namespace
spec:
  project: default
  source:
    repoURL: 'https://matheusfm.dev/charts'  # Correct Helm repository URL
    chart: httpbin                         # The chart name
    targetRevision: latest                 # You can specify a version or use 'latest'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default                      # Target deployment namespace (can be changed if needed)
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      