apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/marwiesing/GitOps_Argo_CD.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc 
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true