apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/nginx
  - ../../base/caddy

namespace: default

patches:
  - path: patch.yaml
    target:
      kind: Ingress
      name: caddy-ingress
  - path: patch.yaml
    target:
      kind: Deployment
      name: nginx-deployment
