apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/nginx
  - ../../base/caddy

namespace: default

patches:
  - patch.yaml

configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile
